---
- hosts: all
  tasks:
    - name: Install IUS external repo
      yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=present
    - name: Install Percona external repo
      yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm state=present

    - name: Install virtualenv
      yum: name="python-virtualenv" state=present

    - name: Install virtualenvwrapper
      yum: name="python-virtualenvwrapper" state=present

    - name: Install python34
      yum: name="python34u" state=present

    - name: Install python34-pip
      yum: name="python34u-pip" state=present

    - name: Install python34-devel
      yum: name="python34u-devel" state=present

    - name: Install python34-tools
      yum: name="python34u-tools" state=present

    - name: Install Percona
      yum: name="Percona-Server-server" state=present

    - name: Install Percona-devel
      yum: name="Percona-Server-devel" state=present
